#input- a string text, an integer k, and a 4xk matrix profile 
#output- A Profile-most probable k-mer in Text 
def patternToNumber(pattern):
	if len(pattern) == 0:
		return 0
	return 4 * patternToNumber(pattern[0:-1]) + symbolToNumber(pattern[-1:])

def symbolToNumber(symbol):
	if symbol == "A":
		return 0
	if symbol == "C":
		return 1
	if symbol == "G":
		return 2
	if symbol == "T":
		return 3

def numberToPattern(x, k):
	if k == 1:
		return numberToSymbol(x)
	return numberToPattern(x // 4, k-1) + numberToSymbol(x % 4)

def numberToSymbol(x):
	if x == 0:
		return "A"
	if x == 1:
		return "C"
	if x == 2:
		return "G"
	if x == 3:
		return "T"

def profileProbable(text, k, profile):
	probs = [0] * 4**k
	for i in range(len(text) - k +1):
		prob = 1
		pattern = text[i:i+k]
		for j in range(k):
			l = symbolToNumber(pattern[j])
			prob *= profile[l][j]
		probs[patternToNumber(pattern)] = prob
	m = max(probs)
	for x in range(4**k):
		if probs[x] == m:
			return numberToPattern(x, k)


#dataset_609081_3.txt
text = "CCTTACCAATCGAACACCTATGGAGCATAAATTCACCGGCTGCCTGGGCTGCTCTACGCGTCCTGCGCCAAGCGAGGAGCGACCGCGCGTTTACACTTCCCTATCGTTTCGATGGACTGGAAGGACGCCTCTGAGTGTTAGAGCCCCAACACATCTCTAAATCCTGTTACAGAGCCCTGGTTAGACTGGTTTCAGGGGTGTCATTGGAAGGATACCATTCCCCCCAACTGCCGTCCCGTAGGAAGTTTGTGCTAACAGTGTCGTCAGTTTGATTGAACCTGTGAGATCGCCGGAGAATCGCAATCCCCGGGTGGTGAGGGCTGGGCAGATGATCACAGTAAGAAACGAAATATAAGGAGTCGTGGCACTCTCTCCAATCACTCAACAAAATAGGTGATGAACATTGACATACACAGAGCGCACGAATGCAGCGTTGTGGATCTTTGGACAAATAGGTGAACATATAGACTATAAGGGATCGTGTCGTCAAACCAGAATCTGGAGAATTGAAATCTGTTTGATCCGCTGAGGAGATGATGGCTGCCGGTATTACCGGTTCATTCATACGAGATACCGCGTACCGAGGGCGCAGAGCCTACAAACTGGGCATGCAAGTTTCTCGAGGGGACGAATCAAAAAGCTATGTTATCGCCACAAAGAATCTTGCCGAGCAGGAATCAACTAATGGCATCTCTTCAGGTATGTCTGAACCTCATCCTAATGAAGATAAGGAAACCCATGAGAACTAATCGTGTTTGTCAGAGAGCCTAACCCGTTTTTTACCTCCGATGCAGGGCCGGCAACTGGCGTTGCTTCCCATGGAAAAATGGGCTCTACGCACAGCATTCGGTTATTTTACGTCACTACTTAGACGCGTATAACAAATAAACCACTCCCCTGAAGTGGTTCGCTCCCCCGCACTTGAGCAGTGGTTTTTTCAGCTGTATGACCCAAGGGTACAGACATGTAAGGGATGCATGCGCGACCTACCCATACAACG"
k = 12
profile = [[0.313, 0.337, 0.193, 0.193, 0.229, 0.265, 0.386, 0.193, 0.217, 0.157, 0.205, 0.289],
[0.205, 0.193, 0.277, 0.229, 0.301, 0.301, 0.217, 0.217, 0.265, 0.193, 0.205, 0.181],
[0.265, 0.265, 0.265, 0.349, 0.253, 0.133, 0.145, 0.337, 0.253, 0.349, 0.289, 0.301],
[0.217, 0.205, 0.265, 0.229, 0.217, 0.301, 0.253, 0.253, 0.265, 0.301, 0.301, 0.229]]
print(profile)

print(profileProbable(text, k, profile))